name: Publish JSON Schema
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.owner == "stac-extensions" && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Inject env variables
        uses: rlespinasse/github-slug-action@v4.4.1
      - uses: actions/checkout@v4
      - name: deploy JSON Schema for version ${{ env.GITHUB_REF_SLUG }}
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: json-schema
          destination_dir: ${{ env.GITHUB_REF_SLUG }}
